name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install npm
        run: npm install --global npm@9
      - name: Install pnpm
        run: npm install --global pnpm@7
      - name: Install Dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install npm
        run: npm install --global npm@9
      - name: Install pnpm
        run: npm install --global pnpm@7
      - name: Install Dependencies
        run: pnpm install
      - name: Test
        run: pnpm run test
